# This is a basic workflow to help you get started with Actions

name: Project Health

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Setup MSBuild
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
    # Setup Nuget
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.2
    # Restore package
    - name: Build-project
      run: nuget restore Net.Xmpp.sln
    # Build project
    - name: Build-project
      run: msbuild Net.Xmpp.sln /p:Configuration=Release /t:Rebuild
    # Check reamde links
    - name: HashiCorp's Link Checker
      uses: hashicorp/gh-action-check-broken-links@v1.0.1
      with:
        # A list of files that will be scanned for the presence of links
        files: Readme.md
